version: '3.9'
services:
  web:
    build: .
    container_name: project_assesment
    ports:
      - "9601:9601"
    environment:
      POSTGRES_DB: projects_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: projects_db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
